export const theme = {
  ERROR: "#c80000",
  BASE_BORDER_RADIUS: "3px",
  BASE_BG: "#404b69",
  BASE_TEXT_COLOR: "#ffffff",
  // Header
  HEADER_BG: "#283149",
  HEADER_TEXT_COLOR: "#ffffff",
  // Table
  TABLE_TEXT_COLOR: "#fff",
  TABLE_BG_COLOR: "#323d5a",
  TABLE_BORDER_COLOR: "#283149",
  TABLE_HEADER_BG_COLOR: "#283149",
  // Button
  BTN_BG_COLOR: "#4189ff",
  BTN_BORDER_COLOR: "#4189ff",
  BTN_TEXT_COLOR: "#fff",
  BTN_ACTIVE_BG_COLOR: "#3380ff",
  BTN_DISABLED_BG_COLOR: "#6676a2",
  BTN_DISABLED_TEXT_COLOR: "#8498d0",
  BTN_DISABLED_BORDER_COLOR: "#6676a2",
  ICON_BUTTON_BORDER_RADIUS: "100%",
  ICON_BUTTON_BG: "#d2d2d2",
  ICON_BUTTON_BORDER_COLOR: "#d2d2d2",
  ICON_BUTTON_PRIMARY_BG: "#329bff",
  ICON_BUTTON_PRIMARY_BORDER_COLOR: "#329bff",
  ICON_BUTTON_TEXT_COLOR: "#333",
  ICON_BUTTON_PRIMARY_TEXT_COLOR: "#fff",
  ICON_BUTTON_BG_HOVER: "#b7b7b7",
  ICON_BUTTON_PRIMARY_BG_HOVER: "#2d8fec",
  ICON_BUTTON_BORDER_COLOR_HOVER: "#b7b7b7",
  ICON_BUTTON_PRIMARY_BORDER_COLOR_HOVER: "#2d8fec",

  LINK_BTN_TEXT_COLOR: "#61dafb",
  LINK_BTN_TEXT_ACTIVE_COLOR: "#04b4e4",
  LINK_BTN_TEXT_DISABLED_COLOR: "#6676a2",
  // Form
  LABEL_TEXT: "#b4b5b7",
  LABEL_VALUE: "#ffffff",
  FORM_CONTROL_BG: "#323d5a",
  FORM_CONTROL_PLACEHOLDER_TEXT_COLOR: "#b4b5b7",
  FORM_CONTROL_BORDER_COLOR: "#283149",
  FORM_CONTROL_TEXT_COLOR: "#ffffff",
  // Modal
  MODAL_BG: "#283149",
  MODAL_BORDER: "#323d5a",
  BACKDROP_BG: "rgba(1, 1, 1, 0.7)",
  // Message
  MESSAGE_TEXT_COLOR: "#ffffff",
  MESSAGE_TEXT_COLOR_ERROR: "#c80000",
  // Loader
  LOADER_TEXT_COLOR: "#ffffff",
  LOADER_COLOR: "#ffffff"
};

type ThemeType = typeof theme;

export default ThemeType;
